variable "name" {
  description = "Name of the AWS Transfer Server"
  type        = string
}

variable "iam_role_name" {
  description = "Name of the AWS Transfer Server IAM Role used for logging to CloudWatch Logs"
  type        = string
  default     = "sftp-logging-role"
}

variable "iam_role_description" {
  description = "Description of the AWS Transfer Server IAM Role used for logging to CloudWatch Logs"
  type        = string
  default     = "IAM Role used by AWS Transfer Server to log to Cloudwatch"
}

variable "zone_id" {
  description = "Route53 Zone ID of the SFTP Endpoint CNAME record.  Also requires domain_name."
  type        = string
  default     = ""
}

variable "domain_name" {
  description = "Domain name of the SFTP Endpoint as a CNAME record.  Also requires zone_id."
  type        = string
  default     = ""
}

variable "tags" {
  type        = map(string)
  description = "Additional tags"
  default     = {}
}

variable "endpoint_type" {
  type        = string
  description = "The type of endpoint that you want your SFTP server connect to. Either PUBLIC or VPC."
  default     = "PUBLIC"
}

variable "endpoint_details" {
  type        = map(object({
    address_allocation_ids = list(string)
    subnet_ids             = list(string)
    vpc_id                 = string
    security_group_ids     = list(string)
  }))
  description = "The virtual private cloud (VPC) endpoint settings that you want to configure for your SFTP server. Only required if endpoint_type is set to VPC."
  default     = {}
}

variable "protocols" {
  type        = list(string)
  description = "Specifies the file transfer protocol or protocols over which your file transfer protocol client can connect to your server's endpoint."
  default     = ["SFTP"]
}

variable "security_policy_name" {
  type        = string
  description = "Specifies the name of the security policy that is attached to the server."
  default     = "TransferSecurityPolicy-2020-06"
}

variable "host_key" {
  type        = string
  description = "RSA private key (e.g., as generated by the ssh-keygen -N \"\" -m PEM -f my-new-server-key command)."
  default     = null
}

variable "certificate" {
  type        = string
  description = "The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM) certificate."
  default     = null
}
